name: Test

on:
  [push]
  
env:
  dotapns_tests_p8_contents: ${{secrets.DOTAPNS_TESTS_P8_CONTENTS}}
  dotapns_tests_p8_path: ${{secrets.DOTAPNS_TESTS_P8_PATH}}
  dotapns_tests_p12_base64enc: ${{secrets.DOTAPNS_TESTS_P12_BASE64ENC}}  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0'
    - name: Create test JWT file
      run: echo "$dotapns_tests_p8_contents" > "jwt.p8"
      shell: bash
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      if: matrix.os == 'windows-latest'
      run: dotnet nuget locals all --clear
    - name: Test for .NET 6
      run: dotnet test --no-build --verbosity normal --framework net6.0
    - name: Test for .NET Framework 4.6
      if: matrix.os == 'windows-latest'
      run: dotnet test --no-build --verbosity normal --framework net46
